export const LOAD_HOME_PAGE_DATA = "LOAD_HOME_PAGE_DATA";
export const LOAD_GEO = "LOAD_GEO";
export const CHANGE_ACTIVE_DETAIL_PANE = "CHANGE_ACTIVE_DETAIL_PANE";
export const LOAD_QUICK_GAME_DATA = "LOAD_QUICK_GAME_DATA";
